// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSoTEtxc57J3XuN080oBwHnPi877YtG0',
    appId: '1:96904726096:ios:3b8393fc466741c77e7355',
    messagingSenderId: '96904726096',
    projectId: 'sugackselers',
    storageBucket: 'sugackselers.firebasestorage.app',
    iosBundleId: 'com.ragabaat.sugacke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlaB5dzPjb9hZkJNlXPKXnmZZOseQ4rYk',
    appId: '1:96904726096:web:28ae07426f810de07e7355',
    messagingSenderId: '96904726096',
    projectId: 'sugackselers',
    authDomain: 'sugackselers.firebaseapp.com',
    storageBucket: 'sugackselers.firebasestorage.app',
    measurementId: 'G-FYG33QPXSR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlaB5dzPjb9hZkJNlXPKXnmZZOseQ4rYk',
    appId: '1:96904726096:web:28ae07426f810de07e7355',
    messagingSenderId: '96904726096',
    projectId: 'sugackselers',
    authDomain: 'sugackselers.firebaseapp.com',
    storageBucket: 'sugackselers.firebasestorage.app',
    measurementId: 'G-FYG33QPXSR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSoTEtxc57J3XuN080oBwHnPi877YtG0',
    appId: '1:96904726096:ios:3b8393fc466741c77e7355',
    messagingSenderId: '96904726096',
    projectId: 'sugackselers',
    storageBucket: 'sugackselers.firebasestorage.app',
    iosBundleId: 'com.ragabaat.sugacke',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDudlPj1PV60LFq94818Nu2S0Qg0SfxoYM',
    appId: '1:96904726096:android:ad9199e1daa3c1ee7e7355',
    messagingSenderId: '96904726096',
    projectId: 'sugackselers',
    storageBucket: 'sugackselers.firebasestorage.app',
  );

}